project:
  type: website
  output-dir: docs

website:
  title: "Jiwon Qmd 블로그"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://sallyshin01.github.io/jiwon-blog/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



